import type { POI } from "@/types/database";
import { SANTA_FE_POIS } from "./santa-fe-dummy-data";

export type SupportedLocale = "es" | "en" | "pt" | "zh";
// Break circular dependency: SupportedLocale is now defined locally here too.
type LocalizedValue<T> = Record<SupportedLocale, T>;

interface LocalizedProductSeed {
  id: string;
  precio: number;
  nombre: LocalizedValue<string>;
  descripcion: LocalizedValue<string>;
}

interface PoiSeed {
  id: string;
  nombre: string;
  categoria: POI["categoria"];
  latitud: number;
  longitud: number;
  direccion: string;
  emoji: string;
  foto_url: string;
  verificado: boolean;
  activo: boolean;
  precio_rango: LocalizedValue<string>;
  horario_apertura: string;
  horario_cierre: string;
  descripcion: LocalizedValue<string>;
  especialidades: LocalizedValue<string[]>;
  telefono: string;
  instagram: string;
  facebook: string;
  productos: LocalizedProductSeed[];
}

const allLocales = <T>(value: T): LocalizedValue<T> => ({
  es: value,
  en: value,
  pt: value,
  zh: value,
});

const product = (id: string, nombre: string, precio: number, descripcion: string): LocalizedProductSeed => ({
  id,
  precio,
  nombre: allLocales(nombre),
  descripcion: allLocales(descripcion),
});

const PLACE_IMAGE_URLS = {
  angel: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Angel_de_la_independencia_2n.jpg",
  bellasArtes: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Palacio_de_Bellas_Artes_-_CDMX.jpg",
  castilloChapultepec: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Castillo_de_Chapultepec_%28Museo_Nacional_de_Historia%29.JPG",
  soumaya: "https://upload.wikimedia.org/wikipedia/commons/4/43/Museo_Soumaya%2C_Ciudad_de_M%C3%A9xico.jpg",
  antropologia: "https://upload.wikimedia.org/wikipedia/commons/7/74/Museo_Nacional_de_Antropologia.JPG",
  frida: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Museo_Frida_Kahlo.jpg",
  temploMayor: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Templo_mayor_mexico_city.JPG",
  auditorio: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Auditorio_Nacional_Mexico.jpg",
  palacioDeportes: "https://upload.wikimedia.org/wikipedia/commons/d/df/Palacio_de_los_Deportes_%28Mexico_City%29.jpg",
  foroSol: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Foro_Sol_CDMX.jpg",
  wework: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop",
  hospital: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=1200&auto=format&fit=crop",
  coworking: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1200&auto=format&fit=crop",
  tacos: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?q=80&w=1200&auto=format&fit=crop",
  restaurant: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200&auto=format&fit=crop",
  coffee: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=1200&auto=format&fit=crop",
  hotel: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1200&auto=format&fit=crop",
  suite: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?q=80&w=1200&auto=format&fit=crop",
} as const;

export const CURATED_PLACE_IMAGES: Record<string, string> = {
  "Ángel de la Independencia": PLACE_IMAGE_URLS.angel,
  "Palacio de Bellas Artes": PLACE_IMAGE_URLS.bellasArtes,
  "Castillo de Chapultepec": PLACE_IMAGE_URLS.castilloChapultepec,
  "Museo Soumaya": PLACE_IMAGE_URLS.soumaya,
};

export const HOME_IMAGE_URLS = {
  hero: {
    angel: PLACE_IMAGE_URLS.angel,
    bellasArtes: PLACE_IMAGE_URLS.bellasArtes,
    chapultepec: PLACE_IMAGE_URLS.castilloChapultepec,
  },
  categories: {
    gastronomia: PLACE_IMAGE_URLS.tacos,
    hospedaje: PLACE_IMAGE_URLS.hotel,
    cultural: PLACE_IMAGE_URLS.soumaya,
    eventos: PLACE_IMAGE_URLS.auditorio,
    servicios: PLACE_IMAGE_URLS.wework,
  },
  trends: {
    sanMiguel: "https://commons.wikimedia.org/wiki/Special:FilePath/San_Miguel_de_Allende,_Guanajuato,_Mexico..JPG",
    puertoEscondido: "https://commons.wikimedia.org/wiki/Special:FilePath/Puerto_Escondido_Oaxaca.jpg",
  },
};

const POI_SEEDS: PoiSeed[] = [
  {
    id: "justino-demo-id",
    nombre: "Tacos Don Tino (Justino)",
    categoria: "comida",
    latitud: 19.3615,
    longitud: -99.2740,
    direccion: "Av. Vasco de Quiroga 3800, Santa Fe (Puesto Muul)",
    emoji: "🌮",
    foto_url: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?q=80&w=1200&auto=format&fit=crop",
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$"),
    horario_apertura: "09:00",
    horario_cierre: "21:00",
    descripcion: allLocales("Los mejores tacos al pastor de Santa Fe. Receta secreta de Don Tino, ahora en la plataforma Muul."),
    especialidades: allLocales(["Tacos al Pastor", "Gringas", "Aguas Frescas"]),
    telefono: "55 1234 5678",
    instagram: "@tacosdontino",
    facebook: "TacosDonTinoOficial",
    productos: [
      product("p1", "Orden de 5 Tacos al Pastor", 85, "Con piña, cebolla y cilantro."),
      product("p2", "Gringa Especial", 65, "Queso derretido y carne al pastor en tortilla de harina."),
    ],
  },
  {
    id: "gastro-base-debug",
    nombre: "Restaurante de Prueba",
    categoria: "comida",
    latitud: 19.4326,
    longitud: -99.1332,
    direccion: "Calle Falsa 123, CDMX",
    emoji: "🍽️",
    foto_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200",
    verificado: true,
    activo: true,
    precio_rango: allLocales("$"),
    horario_apertura: "08:00",
    horario_cierre: "22:00",
    descripcion: allLocales("Un restaurante de prueba para asegurar que los datos cargan."),
    especialidades: allLocales(["Prueba 1", "Prueba 2"]),
    telefono: "55 1234 5678",
    instagram: "test",
    facebook: "test",
    productos: [],
  },
  ...SANTA_FE_POIS,
  {
    id: "tienda-coppel-reforma-222",
    nombre: "Coppel Reforma 222",
    categoria: "tienda",
    latitud: 19.4275,
    longitud: -99.1638,
    direccion: "Av. Paseo de la Reforma 222, Juárez, Cuauhtémoc, CDMX",
    emoji: "🛍️",
    foto_url: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?q=80&w=1000",
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$"),
    horario_apertura: "10:00",
    horario_cierre: "21:00",
    descripcion: allLocales("Tu tienda Coppel en el corazón de Reforma. Encuentra lo último en tecnología, moda y servicios financieros BanCoppel."),
    especialidades: allLocales(["Celulares", "Crédito Coppel", "Moda"]),
    telefono: "55 5533 1234",
    instagram: "coppel",
    facebook: "TiendasCoppel",
    productos: [
      product("cp1", "Samsung Galaxy S24 Ultra", 26999, "Libre de fábrica, 256GB."),
      product("cp2", "Tenis Nike Air Max", 2499, "Disponible en varias tallas."),
    ],
  },
  {
    id: "tienda-artesanias-ciudadela",
    nombre: "Mercado de Artesanías La Ciudadela",
    categoria: "tienda",
    latitud: 19.4312,
    longitud: -99.1485,
    direccion: "Balderas S/N, Centro, Cuauhtémoc, CDMX",
    emoji: "🎨",
    foto_url: "https://images.unsplash.com/photo-1512418490979-92798ccc13a0?q=80&w=1000",
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$"),
    horario_apertura: "10:00",
    horario_cierre: "19:00",
    descripcion: allLocales("El mercado de artesanías más tradicional de la ciudad. Alebrijes, textiles, cerámica y joyería de todo México."),
    especialidades: allLocales(["Alebrijes", "Textiles de Oaxaca", "Plata de Taxco"]),
    telefono: "55 5510 1234",
    instagram: "laciudadela",
    facebook: "ArtesaniasCiudadela",
    productos: [
      product("art1", "Alebrije de Madera Mediano", 850, "Tallado y pintado a mano en Oaxaca."),
      product("art2", "Huipil Bordado Chiapas", 1200, "Textil artesanal hecho en telar de cintura."),
    ],
  },
  {
    id: "tienda-pendulo-roma",
    nombre: "Librería El Péndulo Roma",
    categoria: "tienda",
    latitud: 19.4125,
    longitud: -99.1625,
    direccion: "Álvaro Obregón 86, Roma Norte, CDMX",
    emoji: "📚",
    foto_url: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?q=80&w=1000",
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$"),
    horario_apertura: "08:00",
    horario_cierre: "23:00",
    descripcion: allLocales("Una de las librerías-café más bellas del mundo. Libros, música, café y cultura en un solo lugar."),
    especialidades: allLocales(["Libros de Arte", "Vinilos", "Cafetería"]),
    telefono: "55 5574 7034",
    instagram: "el_pendulo",
    facebook: "ElPenduloRoma",
    productos: [
      product("bk1", "México: Una Historia Visual", 580, "Libro de pasta dura con fotos históricas."),
      product("bk2", "Café de Grano Casa Péndulo", 240, "Mezcla de la casa 500g."),
    ],
  },
  // GASTRONOMIA (5)
  {
    id: "gastro-taqueria-orinoco-roma",
    nombre: "Taquería Orinoco Roma",
    categoria: "comida",
    latitud: 19.4128,
    longitud: -99.1634,
    direccion: "Av. Álvaro Obregón 100, Roma Norte, Cuauhtémoc, CDMX",
    emoji: "🌮",
    foto_url: PLACE_IMAGE_URLS.tacos,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$"),
    horario_apertura: "13:00",
    horario_cierre: "02:00",
    descripcion: allLocales("Taquería popular en Roma Norte, ideal para pastor, chicharrón y campechano en horario extendido."),
    especialidades: allLocales(["Taco de pastor", "Taco de chicharrón", "Agua fresca"]),
    telefono: "55 5555 0101",
    instagram: "orinoco_taqueria",
    facebook: "OrinocoTaqueria",
    productos: [
      product("p1", "Orden de 5 tacos al pastor", 95, "Incluye cebolla, cilantro y salsa."),
      product("p2", "Volcán de chicharrón", 58, "Tortilla dorada con queso y carne."),
    ],
  },
  {
    id: "gastro-contramar",
    nombre: "Contramar",
    categoria: "comida",
    latitud: 19.4151,
    longitud: -99.171,
    direccion: "Durango 200, Roma Norte, Cuauhtémoc, CDMX",
    emoji: "🐟",
    foto_url: PLACE_IMAGE_URLS.restaurant,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$"),
    horario_apertura: "12:00",
    horario_cierre: "22:00",
    descripcion: allLocales("Restaurante emblemático de mariscos en Roma Norte, reconocido por su tostada de atún y pescado a la talla."),
    especialidades: allLocales(["Tostada de atún", "Pescado a la talla", "Mezcalina de la casa"]),
    telefono: "55 5514 3169",
    instagram: "contramarmx",
    facebook: "Contramar",
    productos: [
      product("p1", "Tostada de atún", 145, "Con mayonesa de chipotle y poro frito."),
      product("p2", "Pescado a la talla (para compartir)", 690, "Mitad adobo rojo y mitad perejil."),
    ],
  },
  {
    id: "gastro-pujol",
    nombre: "Pujol",
    categoria: "comida",
    latitud: 19.4326,
    longitud: -99.1945,
    direccion: "Tennyson 133, Polanco, Miguel Hidalgo, CDMX",
    emoji: "🍽️",
    foto_url: PLACE_IMAGE_URLS.restaurant,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$$"),
    horario_apertura: "13:30",
    horario_cierre: "23:00",
    descripcion: allLocales("Restaurante de alta cocina mexicana contemporánea en Polanco con menú degustación y maridaje."),
    especialidades: allLocales(["Menú degustación", "Mole madre", "Maridaje mexicano"]),
    telefono: "55 5545 3507",
    instagram: "pujolrestaurant",
    facebook: "Pujol",
    productos: [
      product("p1", "Menú degustación", 3890, "Experiencia de varios tiempos."),
      product("p2", "Maridaje de vinos", 2300, "Selección curada por sommelier."),
    ],
  },
  {
    id: "gastro-azul-historico",
    nombre: "Azul Histórico",
    categoria: "comida",
    latitud: 19.4329,
    longitud: -99.1376,
    direccion: "Isabel la Católica 30, Centro Histórico, Cuauhtémoc, CDMX",
    emoji: "🥘",
    foto_url: PLACE_IMAGE_URLS.restaurant,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$"),
    horario_apertura: "09:00",
    horario_cierre: "22:00",
    descripcion: allLocales("Cocina tradicional mexicana en un patio histórico del Centro, excelente para desayuno y comida típica."),
    especialidades: allLocales(["Enchiladas de mole", "Chile en nogada (temporada)", "Chocolate oaxaqueño"]),
    telefono: "55 5510 1316",
    instagram: "azulrestaurantes",
    facebook: "AzulHistorico",
    productos: [
      product("p1", "Enchiladas de mole", 245, "Receta tradicional con ajonjolí."),
      product("p2", "Chocolate de metate", 85, "Bebida caliente de cacao."),
    ],
  },
  {
    id: "gastro-cafe-avellaneda",
    nombre: "Café Avellaneda Coyoacán",
    categoria: "comida",
    latitud: 19.3529,
    longitud: -99.1625,
    direccion: "Higuera 40-B, Coyoacán, CDMX",
    emoji: "☕",
    foto_url: PLACE_IMAGE_URLS.coffee,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$"),
    horario_apertura: "08:00",
    horario_cierre: "20:00",
    descripcion: allLocales("Cafetería de especialidad en Coyoacán con métodos filtrados y granos mexicanos de temporada."),
    especialidades: allLocales(["V60", "Flat white", "Pan dulce artesanal"]),
    telefono: "55 5555 0105",
    instagram: "cafeavellaneda",
    facebook: "CafeAvellaneda",
    productos: [
      product("p1", "Flat white", 78, "Doble espresso con leche texturizada."),
      product("p2", "V60 origen Chiapas", 85, "Extracción filtrada de temporada."),
    ],
  },

  // HOSPEDAJE (5)
  {
    id: "hospedaje-four-seasons-reforma",
    nombre: "Four Seasons Hotel Mexico City",
    categoria: "hospedaje",
    latitud: 19.4249,
    longitud: -99.1711,
    direccion: "Paseo de la Reforma 500, Juárez, Cuauhtémoc, CDMX",
    emoji: "🏨",
    foto_url: PLACE_IMAGE_URLS.hotel,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$$"),
    horario_apertura: "00:00",
    horario_cierre: "23:59",
    descripcion: allLocales("Hotel de lujo sobre Reforma con patio central, spa y acceso estratégico a Chapultepec y Polanco."),
    especialidades: allLocales(["Suite ejecutiva", "Spa", "Room service 24h"]),
    telefono: "55 5230 1818",
    instagram: "fsmexicocity",
    facebook: "FourSeasonsMexicoCity",
    productos: [
      product("p1", "Noche en habitación deluxe", 11900, "Tarifa promedio por noche."),
      product("p2", "Desayuno buffet", 780, "Disponible para huéspedes y visitantes."),
    ],
  },
  {
    id: "hospedaje-sofitel-reforma",
    nombre: "Sofitel Mexico City Reforma",
    categoria: "hospedaje",
    latitud: 19.4278,
    longitud: -99.1651,
    direccion: "Paseo de la Reforma 297, Cuauhtémoc, CDMX",
    emoji: "🛎️",
    foto_url: PLACE_IMAGE_URLS.suite,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$$"),
    horario_apertura: "00:00",
    horario_cierre: "23:59",
    descripcion: allLocales("Hotel cinco estrellas con rooftop y vista panorámica al Ángel de la Independencia."),
    especialidades: allLocales(["Habitación skyline", "Rooftop bar", "Alberca interior"]),
    telefono: "55 8660 0500",
    instagram: "sofitelmexicocity",
    facebook: "SofitelMexicoCity",
    productos: [
      product("p1", "Noche en habitación superior", 9800, "Tarifa promedio por noche."),
      product("p2", "Acceso day pass spa", 1650, "Incluye zona húmeda."),
    ],
  },
  {
    id: "hospedaje-gran-hotel-zocalo",
    nombre: "Gran Hotel Ciudad de México",
    categoria: "hospedaje",
    latitud: 19.4316,
    longitud: -99.1333,
    direccion: "Av. 16 de Septiembre 82, Centro Histórico, CDMX",
    emoji: "🏛️",
    foto_url: PLACE_IMAGE_URLS.hotel,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$"),
    horario_apertura: "00:00",
    horario_cierre: "23:59",
    descripcion: allLocales("Hotel histórico frente al Zócalo con arquitectura porfiriana y terraza con vista a Catedral."),
    especialidades: allLocales(["Habitación con balcón al Zócalo", "Restaurante rooftop", "Experiencia histórica"]),
    telefono: "55 1083 7700",
    instagram: "granhotelcdmx",
    facebook: "GranHotelCiudadDeMexico",
    productos: [
      product("p1", "Noche en habitación histórica", 5400, "Tarifa promedio por noche."),
      product("p2", "Cena en terraza", 980, "Menú de tres tiempos."),
    ],
  },
  {
    id: "hospedaje-st-regis-reforma",
    nombre: "The St. Regis Mexico City",
    categoria: "hospedaje",
    latitud: 19.4258,
    longitud: -99.1705,
    direccion: "Paseo de la Reforma 439, Cuauhtémoc, CDMX",
    emoji: "✨",
    foto_url: PLACE_IMAGE_URLS.suite,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$$"),
    horario_apertura: "00:00",
    horario_cierre: "23:59",
    descripcion: allLocales("Hospedaje premium en Reforma con servicio de mayordomo y habitaciones de alto nivel."),
    especialidades: allLocales(["Suite Reforma", "Mayordomo", "Spa de lujo"]),
    telefono: "55 5228 1818",
    instagram: "stregismexicocity",
    facebook: "StRegisMexicoCity",
    productos: [
      product("p1", "Noche en suite junior", 13400, "Tarifa promedio por noche."),
      product("p2", "Brunch dominical", 1250, "Incluye estación gourmet."),
    ],
  },
  {
    id: "hospedaje-hilton-alameda",
    nombre: "Hilton Mexico City Reforma",
    categoria: "hospedaje",
    latitud: 19.4356,
    longitud: -99.1458,
    direccion: "Av. Juárez 70, Centro Histórico, CDMX",
    emoji: "🛏️",
    foto_url: PLACE_IMAGE_URLS.hotel,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$"),
    horario_apertura: "00:00",
    horario_cierre: "23:59",
    descripcion: allLocales("Hotel frente a la Alameda Central, conveniente para turismo cultural y eventos en el Centro."),
    especialidades: allLocales(["Habitación ejecutiva", "Centro de negocios", "Alberca"]),
    telefono: "55 5130 5300",
    instagram: "hiltonreforma",
    facebook: "HiltonMexicoCityReforma",
    productos: [
      product("p1", "Noche en habitación ejecutiva", 5900, "Tarifa promedio por noche."),
      product("p2", "Acceso lounge ejecutivo", 900, "Bebidas y bocadillos incluidos."),
    ],
  },

  // CULTURAL (5)
  {
    id: "cultural-angel-independencia",
    nombre: "Ángel de la Independencia",
    categoria: "cultural",
    latitud: 19.427,
    longitud: -99.1677,
    direccion: "Paseo de la Reforma, Juárez, Cuauhtémoc, CDMX",
    emoji: "🗽",
    foto_url: PLACE_IMAGE_URLS.angel,
    verificado: true,
    activo: true,
    precio_rango: allLocales("Gratis"),
    horario_apertura: "00:00",
    horario_cierre: "23:59",
    descripcion: allLocales("Monumento icónico de la ciudad y punto de encuentro para celebraciones y recorridos históricos en Reforma."),
    especialidades: allLocales(["Fotografía urbana", "Recorrido histórico", "Vista nocturna"]),
    telefono: "55 5555 0301",
    instagram: "angelindependencia",
    facebook: "AngelDeLaIndependenciaCDMX",
    productos: [
      product("p1", "Tour histórico a pie", 180, "Recorrido guiado por Reforma."),
      product("p2", "Sesión fotográfica express", 650, "30 minutos alrededor del monumento."),
    ],
  },
  {
    id: "cultural-bellas-artes",
    nombre: "Palacio de Bellas Artes",
    categoria: "cultural",
    latitud: 19.4352,
    longitud: -99.1412,
    direccion: "Av. Juárez S/N, Centro Histórico, Cuauhtémoc, CDMX",
    emoji: "🎭",
    foto_url: PLACE_IMAGE_URLS.bellasArtes,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$"),
    horario_apertura: "10:00",
    horario_cierre: "18:00",
    descripcion: allLocales("Recinto cultural insignia del país con murales, exposiciones temporales y programación escénica."),
    especialidades: allLocales(["Murales de Rivera", "Exposición temporal", "Arquitectura art nouveau"]),
    telefono: "55 8647 6500",
    instagram: "palaciobellasartes",
    facebook: "PalacioDeBellasArtes",
    productos: [
      product("p1", "Entrada general museo", 90, "Acceso a salas permanentes y temporales."),
      product("p2", "Boleto función nocturna", 420, "Costo promedio por evento."),
    ],
  },
  {
    id: "cultural-castillo-chapultepec",
    nombre: "Castillo de Chapultepec",
    categoria: "cultural",
    latitud: 19.4204,
    longitud: -99.1819,
    direccion: "Bosque de Chapultepec I Sección, Miguel Hidalgo, CDMX",
    emoji: "🏰",
    foto_url: PLACE_IMAGE_URLS.castilloChapultepec,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$"),
    horario_apertura: "09:00",
    horario_cierre: "17:00",
    descripcion: allLocales("Museo Nacional de Historia ubicado en el castillo, con salas históricas y vista panorámica de la ciudad."),
    especialidades: allLocales(["Salones imperiales", "Museo de Historia", "Mirador"]),
    telefono: "55 4040 5200",
    instagram: "museodehistoria",
    facebook: "CastilloChapultepec",
    productos: [
      product("p1", "Entrada general", 95, "Acceso completo a salas y jardines."),
      product("p2", "Audioguía", 55, "Disponible en varios idiomas."),
    ],
  },
  {
    id: "cultural-antropologia",
    nombre: "Museo Nacional de Antropología",
    categoria: "cultural",
    latitud: 19.426,
    longitud: -99.1861,
    direccion: "Av. Paseo de la Reforma y Calzada Gandhi, Miguel Hidalgo, CDMX",
    emoji: "🏺",
    foto_url: PLACE_IMAGE_URLS.antropologia,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$"),
    horario_apertura: "09:00",
    horario_cierre: "18:00",
    descripcion: allLocales("Uno de los museos más importantes de México, con colecciones prehispánicas y salas etnográficas."),
    especialidades: allLocales(["Piedra del Sol", "Sala Mexica", "Colecciones prehispánicas"]),
    telefono: "55 5553 6266",
    instagram: "mnantropologia",
    facebook: "MuseoNacionalDeAntropologia",
    productos: [
      product("p1", "Entrada general", 95, "Acceso a salas permanentes."),
      product("p2", "Catálogo oficial", 380, "Libro con piezas destacadas."),
    ],
  },
  {
    id: "cultural-museo-frida-kahlo",
    nombre: "Museo Frida Kahlo",
    categoria: "cultural",
    latitud: 19.3553,
    longitud: -99.1627,
    direccion: "Londres 247, Del Carmen, Coyoacán, CDMX",
    emoji: "🎨",
    foto_url: PLACE_IMAGE_URLS.frida,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$"),
    horario_apertura: "10:00",
    horario_cierre: "18:00",
    descripcion: allLocales("La Casa Azul de Frida Kahlo en Coyoacán, con piezas originales y recorrido biográfico."),
    especialidades: allLocales(["Casa Azul", "Colección personal", "Exhibiciones temporales"]),
    telefono: "55 5554 5999",
    instagram: "museofridakahlo",
    facebook: "MuseoFridaKahlo",
    productos: [
      product("p1", "Entrada general", 320, "Costo promedio para visitante nacional."),
      product("p2", "Visita guiada", 480, "Recorrido con guía especializado."),
    ],
  },

  // EVENTOS (5)
  {
    id: "eventos-auditorio-nacional",
    nombre: "Auditorio Nacional",
    categoria: "eventos",
    latitud: 19.425,
    longitud: -99.1947,
    direccion: "Av. Paseo de la Reforma 50, Polanco V Sección, Miguel Hidalgo, CDMX",
    emoji: "🎤",
    foto_url: PLACE_IMAGE_URLS.auditorio,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$"),
    horario_apertura: "10:00",
    horario_cierre: "23:30",
    descripcion: allLocales("Recinto principal para conciertos, espectáculos y giras internacionales en la Ciudad de México."),
    especialidades: allLocales(["Conciertos masivos", "Espectáculos en vivo", "Taquilla oficial"]),
    telefono: "55 9138 1350",
    instagram: "auditorioacional",
    facebook: "AuditorioNacional",
    productos: [
      product("p1", "Boleto concierto zona media", 1450, "Precio referencial por evento."),
      product("p2", "Boleto concierto zona alta", 790, "Precio referencial por evento."),
    ],
  },
  {
    id: "eventos-palacio-deportes",
    nombre: "Palacio de los Deportes",
    categoria: "eventos",
    latitud: 19.4046,
    longitud: -99.0993,
    direccion: "Av. Río Churubusco y Añil S/N, Iztacalco, CDMX",
    emoji: "🎵",
    foto_url: PLACE_IMAGE_URLS.palacioDeportes,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$"),
    horario_apertura: "10:00",
    horario_cierre: "23:30",
    descripcion: allLocales("Recinto emblemático para conciertos y festivales con gran capacidad en la zona oriente."),
    especialidades: allLocales(["Conciertos", "Festivales", "Eventos deportivos"]),
    telefono: "55 5325 9000",
    instagram: "ocesa",
    facebook: "PalacioDeLosDeportes",
    productos: [
      product("p1", "Boleto zona general", 980, "Precio promedio por espectáculo."),
      product("p2", "Boleto zona preferente", 1950, "Precio promedio por espectáculo."),
    ],
  },
  {
    id: "eventos-foro-sol",
    nombre: "Foro Sol",
    categoria: "eventos",
    latitud: 19.4042,
    longitud: -99.0956,
    direccion: "Viad. Río de la Piedad S/N, Granjas México, Iztacalco, CDMX",
    emoji: "🎸",
    foto_url: PLACE_IMAGE_URLS.foroSol,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$"),
    horario_apertura: "12:00",
    horario_cierre: "23:59",
    descripcion: allLocales("Escenario para grandes conciertos y festivales con producción de formato estadio."),
    especialidades: allLocales(["Festivales", "Conciertos internacionales", "Zona general"]),
    telefono: "55 9138 1350",
    instagram: "forosoloficial",
    facebook: "ForoSol",
    productos: [
      product("p1", "Boleto zona general", 1200, "Precio promedio por evento."),
      product("p2", "Boleto zona preferente", 2600, "Precio promedio por evento."),
    ],
  },
  {
    id: "eventos-arena-cdmx",
    nombre: "Arena CDMX",
    categoria: "eventos",
    latitud: 19.4977,
    longitud: -99.1555,
    direccion: "Av. de las Granjas 800, Santa Bárbara, Azcapotzalco, CDMX",
    emoji: "🏟️",
    foto_url: PLACE_IMAGE_URLS.auditorio,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$"),
    horario_apertura: "10:00",
    horario_cierre: "23:30",
    descripcion: allLocales("Arena techada para conciertos, deportes de exhibición y espectáculos familiares."),
    especialidades: allLocales(["Conciertos", "Lucha libre", "Espectáculos familiares"]),
    telefono: "55 3093 1660",
    instagram: "arenacdmx",
    facebook: "ArenaCDMX",
    productos: [
      product("p1", "Boleto zona media", 890, "Precio promedio por evento."),
      product("p2", "Boleto zona VIP", 2100, "Precio promedio por evento."),
    ],
  },
  {
    id: "eventos-pepsi-center-wtc",
    nombre: "Pepsi Center WTC",
    categoria: "eventos",
    latitud: 19.3953,
    longitud: -99.1744,
    direccion: "Dakota S/N, Nápoles, Benito Juárez, CDMX",
    emoji: "🎫",
    foto_url: PLACE_IMAGE_URLS.auditorio,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$"),
    horario_apertura: "11:00",
    horario_cierre: "23:30",
    descripcion: allLocales("Foro de conciertos de mediano formato en la zona WTC, ideal para giras urbanas y eventos especiales."),
    especialidades: allLocales(["Conciertos íntimos", "Stand-up", "Eventos corporativos"]),
    telefono: "55 9000 9000",
    instagram: "pepsicenterwtc",
    facebook: "PepsiCenterWTC",
    productos: [
      product("p1", "Boleto pista general", 680, "Precio promedio por evento."),
      product("p2", "Boleto balcón preferente", 1450, "Precio promedio por evento."),
    ],
  },

  // SERVICIOS (5)
  {
    id: "servicios-wework-reforma-latino",
    nombre: "WeWork Reforma Latino",
    categoria: "servicios",
    latitud: 19.4343,
    longitud: -99.1413,
    direccion: "Paseo de la Reforma 296, Juárez, Cuauhtémoc, CDMX",
    emoji: "💼",
    foto_url: PLACE_IMAGE_URLS.wework,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$"),
    horario_apertura: "08:00",
    horario_cierre: "20:00",
    descripcion: allLocales("Espacio de coworking con salas de juntas y oficinas privadas en la zona centro de Reforma."),
    especialidades: allLocales(["Coworking diario", "Sala de juntas", "Oficina privada"]),
    telefono: "55 4161 5000",
    instagram: "wework",
    facebook: "WeWork",
    productos: [
      product("p1", "Day pass coworking", 650, "Acceso por día en área compartida."),
      product("p2", "Sala de juntas 2 horas", 1200, "Incluye pantalla y café."),
    ],
  },
  {
    id: "servicios-ios-offices-torre-reforma",
    nombre: "IOS Offices Torre Reforma",
    categoria: "servicios",
    latitud: 19.4265,
    longitud: -99.1736,
    direccion: "Paseo de la Reforma 483, Cuauhtémoc, CDMX",
    emoji: "🧑‍💻",
    foto_url: PLACE_IMAGE_URLS.coworking,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$"),
    horario_apertura: "08:00",
    horario_cierre: "19:00",
    descripcion: allLocales("Centro de negocios en Torre Reforma con oficinas equipadas, recepción y espacios flexibles."),
    especialidades: allLocales(["Oficina virtual", "Coworking", "Salas ejecutivas"]),
    telefono: "55 5350 9500",
    instagram: "iosoffices",
    facebook: "IOSOffices",
    productos: [
      product("p1", "Pase diario coworking", 590, "Espacio compartido con internet."),
      product("p2", "Oficina virtual mensual", 2900, "Domicilio comercial y recepción."),
    ],
  },
  {
    id: "servicios-hospital-abc-observatorio",
    nombre: "Hospital ABC Observatorio",
    categoria: "servicios",
    latitud: 19.4046,
    longitud: -99.2052,
    direccion: "Sur 136 116, Las Américas, Álvaro Obregón, CDMX",
    emoji: "🏥",
    foto_url: PLACE_IMAGE_URLS.hospital,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$$"),
    horario_apertura: "00:00",
    horario_cierre: "23:59",
    descripcion: allLocales("Hospital privado de alta especialidad con urgencias 24 horas en la zona poniente de la ciudad."),
    especialidades: allLocales(["Urgencias 24h", "Consulta especializada", "Check-up ejecutivo"]),
    telefono: "55 5230 8000",
    instagram: "centromedicoabc",
    facebook: "CentroMedicoABC",
    productos: [
      product("p1", "Consulta médica general", 1450, "Atención de primer contacto."),
      product("p2", "Check-up ejecutivo", 7800, "Paquete integral de estudios."),
    ],
  },
  {
    id: "servicios-cac-telcel-reforma-222",
    nombre: "CAC Telcel Reforma 222",
    categoria: "servicios",
    latitud: 19.4275,
    longitud: -99.1638,
    direccion: "Paseo de la Reforma 222, Juárez, Cuauhtémoc, CDMX",
    emoji: "📱",
    foto_url: PLACE_IMAGE_URLS.coworking,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$"),
    horario_apertura: "10:00",
    horario_cierre: "20:00",
    descripcion: allLocales("Centro de atención Telcel para contratación de planes, renovación de equipos y soporte técnico."),
    especialidades: allLocales(["Renovación", "Portabilidad", "Soporte de línea"]),
    telefono: "55 5555 0404",
    instagram: "telcel",
    facebook: "Telcel",
    productos: [
      product("p1", "Plan pospago mensual", 499, "Paquete con datos y llamadas."),
      product("p2", "Cambio de SIM", 150, "Reposición y activación inmediata."),
    ],
  },
  {
    id: "servicios-regus-wtc",
    nombre: "Regus WTC Ciudad de México",
    categoria: "servicios",
    latitud: 19.3948,
    longitud: -99.1747,
    direccion: "Montecito 38, Nápoles, Benito Juárez, CDMX",
    emoji: "📊",
    foto_url: PLACE_IMAGE_URLS.wework,
    verificado: true,
    activo: true,
    precio_rango: allLocales("$$$"),
    horario_apertura: "08:00",
    horario_cierre: "20:00",
    descripcion: allLocales("Centro de oficinas y coworking dentro del corredor WTC, con servicios corporativos y salas equipadas."),
    especialidades: allLocales(["Coworking", "Oficina privada", "Sala de videoconferencia"]),
    telefono: "55 9000 1111",
    instagram: "regus_mexico",
    facebook: "Regus",
    productos: [
      product("p1", "Pase diario", 560, "Acceso a espacio flexible."),
      product("p2", "Oficina privada mensual", 8900, "Plan base para 1 persona."),
    ],
  },
];

const normalizeLocale = (locale?: string): SupportedLocale => {
  if (locale === "en" || locale === "pt" || locale === "zh") return locale;
  return "es";
};

export function getLocalizedDummyPois(locale?: string) {
  const safeLocale = normalizeLocale(locale);

  return POI_SEEDS.map((poi) => ({
    id: poi.id,
    nombre: poi.nombre,
    descripcion: poi.descripcion[safeLocale],
    categoria: poi.categoria,
    latitud: poi.latitud,
    longitud: poi.longitud,
    direccion: poi.direccion,
    emoji: poi.emoji,
    foto_url: poi.foto_url,
    verificado: poi.verificado,
    activo: poi.activo,
    precio_rango: poi.precio_rango[safeLocale],
    horario_apertura: poi.horario_apertura,
    horario_cierre: poi.horario_cierre,
    especialidades: poi.especialidades[safeLocale],
    telefono: poi.telefono,
    instagram: poi.instagram,
    facebook: poi.facebook,
    productos: poi.productos.map((item) => ({
      id: item.id,
      nombre: item.nombre[safeLocale],
      precio: item.precio,
      descripcion: item.descripcion[safeLocale],
    })),
    negocio_id: null,
    created_at: "2026-01-01T00:00:00.000Z",
  }));
}

export const DUMMY_POIS = getLocalizedDummyPois("es");
