export const DUMMY_POIS = [
  {
    id: 'dummy-tacos-guero',
    nombre: 'Tacos El Guero',
    descripcion: 'Legendarios tacos al pastor en el corazón del Centro Histórico. Una parada obligatoria para cualquier entusiasta de la gastronomía mexicana.',
    categoria: 'comida',
    latitud: 19.4323,
    longitud: -99.1332,
    direccion: 'Calle República de Uruguay 27, Centro Histórico, CDMX',
    emoji: '🌮',
    foto_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865ef4?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$',
    horario_apertura: '09:00',
    horario_cierre: '23:00',
    especialidades: ['Tacos al Pastor', 'Costra de Queso', 'Agua de Horchata'],
    telefono: '55 1234 5678',
    instagram: 'tacoselguero_mx',
    facebook: 'TacosElGueroOficial',
    productos: [
      { id: 'p1', nombre: 'Orden de 5 Tacos al Pastor', precio: 85, descripcion: 'Con piña, cebolla y cilantro.' },
      { id: 'p2', nombre: 'Gringa de Sirloin', precio: 65, descripcion: 'Queso fundido y carne premium.' }
    ]
  },
  {
    id: 'dummy-coppel-reforma',
    nombre: 'Coppel Reforma',
    descripcion: 'Tu tienda departamental favorita en la avenida más emblemática de México. Lo mejor en moda, tecnología y hogar con la confianza de siempre.',
    categoria: 'tienda',
    latitud: 19.4298,
    longitud: -99.1558,
    direccion: 'Paseo de la Reforma 250, Juárez, CDMX',
    emoji: '🛍️',
    foto_url: 'https://images.unsplash.com/photo-1573855619003-97b4799dcd8b?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '10:00',
    horario_cierre: '20:00',
    especialidades: ['Moda Deportiva', 'Electrónica', 'Hogar Digital'],
    telefono: '800 220 7735',
    instagram: 'coppel',
    facebook: 'tiendascoppel',
    productos: [
      { id: 'p1', nombre: 'Smart TV 4K 55"', precio: 8999, descripcion: 'Lo último en tecnología visual.' },
      { id: 'p2', nombre: 'Tenis de Running', precio: 1299, descripcion: 'Comodidad para tus recorridos por la ciudad.' }
    ]
  },
  {
    id: 'dummy-museo-soumaya',
    nombre: 'Museo Soumaya',
    descripcion: 'Icono arquitectónico que alberga una de las colecciones de arte más importantes del mundo. Un viaje visual desde el Renacimiento hasta el arte moderno.',
    categoria: 'cultural',
    latitud: 19.4407,
    longitud: -99.2047,
    direccion: 'Boulervard Miguel de Cervantes Saavedra 303, Granada, CDMX',
    emoji: '🏛️',
    foto_url: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '10:30',
    horario_cierre: '18:30',
    especialidades: ['Esculturas de Rodin', 'Arte Impresionista', 'Arquitectura Vanguardista'],
    telefono: '55 1103 9800',
    instagram: 'elmuseosoumaya',
    facebook: 'MuseoSoumaya',
    productos: [
      { id: 'p1', nombre: 'Libro de Arte Soumaya', precio: 450, descripcion: 'Toda la colección en tus manos.' },
      { id: 'p2', nombre: 'Tour Privado Curado', precio: 1200, descripcion: 'Explicación profunda de las obras maestras.' }
    ]
  },
  {
    id: 'dummy-coffee-bean',
    nombre: 'The Coffee Bean',
    descripcion: 'El refugio perfecto en Polanco para los amantes del café de especialidad. Granos seleccionados y repostería artesanal en un ambiente relajado.',
    categoria: 'comida',
    latitud: 19.4300,
    longitud: -99.1901,
    direccion: 'Emilio Castelar 135, Polanco, CDMX',
    emoji: '☕',
    foto_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '07:00',
    horario_cierre: '22:00',
    especialidades: ['Cold Brew Nitrogenado', 'Pan de Masa Madre', 'Café Geisha'],
    telefono: '55 9876 5432',
    instagram: 'thecoffeebean_polanco',
    facebook: 'TheCoffeeBeanMX',
    productos: [
      { id: 'p1', nombre: 'Flat White Doble', precio: 75, descripcion: 'Equilibrio perfecto entre espresso y leche seda.' },
      { id: 'p2', nombre: 'Croissant de Almendras', precio: 55, descripcion: 'Horneado diariamente con mantequilla francesa.' }
    ]
  },
  {
    id: 'dummy-angel-independencia',
    nombre: 'Ángel de la Independencia',
    descripcion: 'Monumento emblemático de la Ciudad de México y punto de encuentro para celebraciones nacionales. Un símbolo de libertad envuelto en historia.',
    categoria: 'cultural',
    latitud: 19.4270,
    longitud: -99.1677,
    direccion: 'Paseo de la Reforma y Eje 2 PTE, Juárez, CDMX',
    emoji: '🗽',
    foto_url: 'https://images.unsplash.com/photo-1518182170546-07661fd94144?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: 'Gratis',
    horario_apertura: '00:00',
    horario_cierre: '23:59',
    especialidades: ['Mirador', 'Fotografía', 'Historia Mexicana'],
    telefono: '55 1234 9999',
    instagram: 'angelindependenciamx',
    facebook: 'AngelIndependencia',
    productos: [
      { id: 'p1', nombre: 'Paseo al Mirador', precio: 0, descripcion: 'Sube las escalinatas para una vista a Reforma.' },
      { id: 'p2', nombre: 'Tour Histórico', precio: 150, descripcion: 'Conoce los héroes patrios bajo el monumento.' }
    ]
  },
  {
    id: 'dummy-bellas-artes',
    nombre: 'Palacio de Bellas Artes',
    descripcion: 'La obra arquitectónica más hermosa de la ciudad. Sede de exposiciones, ópera y ballet folklórico.',
    categoria: 'cultural',
    latitud: 19.4352,
    longitud: -99.1412,
    direccion: 'Av. Juárez S/N, Centro Histórico, CDMX',
    emoji: '🎭',
    foto_url: 'https://images.unsplash.com/photo-1585464231473-746d24c039a2?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$$',
    horario_apertura: '10:00',
    horario_cierre: '18:00',
    especialidades: ['Murales de Rivera', 'Ballet Folklórico', 'Exposiciones'],
    telefono: '55 8647 6500',
    instagram: 'palaciooficial',
    facebook: 'BellasArtesMexico',
    productos: [
      { id: 'p1', nombre: 'Entrada General Museo', precio: 85, descripcion: 'Acceso a murales y exposiciones.' },
      { id: 'p2', nombre: 'Boleto Ópera', precio: 500, descripcion: 'Mejores asientos en la sala principal.' }
    ]
  },
  {
    id: 'dummy-chapultepec',
    nombre: 'Castillo de Chapultepec',
    descripcion: 'El único castillo real en América, resguardando la historia imperial y revolucionaria de México con vistas inigualables.',
    categoria: 'cultural',
    latitud: 19.4204,
    longitud: -99.1819,
    direccion: 'Primera Sección del Bosque de Chapultepec, CDMX',
    emoji: '🏰',
    foto_url: 'https://images.unsplash.com/photo-1563911892437-1feda0179e1b?q=80&w=1000&auto=format&fit=crop',
    verificado: true,
    activo: true,
    precio_rango: '$',
    horario_apertura: '09:00',
    horario_cierre: '17:00',
    especialidades: ['Museo Nacional de Historia', 'Habitaciones Imperiales', 'Jardines'],
    telefono: '55 4040 5200',
    instagram: 'museodehistoria',
    facebook: 'CastilloChapultepec',
    productos: [
      { id: 'p1', nombre: 'Entrada General', precio: 90, descripcion: 'Acceso al castillo y áreas verdes.' },
      { id: 'p2', nombre: 'Audioguía', precio: 45, descripcion: 'Recorrido detallado en varios idiomas.' }
    ]
  }
];
